services:
  ml-app:
    build: .
    ports:
      - "8501:8501"
    container_name: ml-app
    volumes:
      - ./files:/app/files
      - ./datasets:/app/datasets
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}